clear all
clc
flexionRatio=50;
shimColor='blue';
filename=strcat('results_',num2str(flexionRatio),'_',shimColor);
load(filename)
timeAvgOfPhzAvgRawPower=[results.timeAvgOfPhzAvgRawPower(:,:,1,1);...
    results.timeAvgOfPhzAvgRawPower(:,:,2,1);...
    results.timeAvgOfPhzAvgRawPower(:,:,3,1);...
    results.timeAvgOfPhzAvgRawPower(:,:,1,2);...
    results.timeAvgOfPhzAvgRawPower(:,:,2,2);...
    results.timeAvgOfPhzAvgRawPower(:,:,3,2)];
airDensity=[results.airDensity(:,:,1,1);...
    results.airDensity(:,:,2,1);...
    results.airDensity(:,:,3,1);...
    results.airDensity(:,:,1,1);...
    results.airDensity(:,:,2,1);...
    results.airDensity(:,:,3,1)];
airVelocity=[results.airVelocity(:,:,1,1);...
    results.airVelocity(:,:,2,1);...
    results.airVelocity(:,:,3,1);...
    results.airVelocity(:,:,1,1);...
    results.airVelocity(:,:,2,1);...
    results.airVelocity(:,:,3,1)];
chordLength=[results.chordLength(:,:,1,1);...
    results.chordLength(:,:,2,1);...
    results.chordLength(:,:,3,1);...
    results.chordLength(:,:,1,2);...
    results.chordLength(:,:,2,2);...
    results.chordLength(:,:,3,2)];
wingSpan=[results.wingSpan(:,:,1,1);...
    results.wingSpan(:,:,2,1);...
    results.wingSpan(:,:,3,1);...
    results.wingSpan(:,:,1,2);...
    results.wingSpan(:,:,2,2);...
    results.wingSpan(:,:,3,2)];
frequency=[results.frequency(:,:,1,1);...
    results.frequency(:,:,2,1);...
    results.frequency(:,:,3,1);...
    results.frequency(:,:,1,1);...
    results.frequency(:,:,2,1);...
    results.frequency(:,:,3,1)];
reducedFreq=2*pi.*frequency.*chordLength./round(airVelocity);
coeffPower=timeAvgOfPhzAvgRawPower./...
    (0.5.*airDensity.*airVelocity.^3.*chordLength.*wingSpan);
meanCoeffPowerWind=mean(coeffPower(1:9,:));
errCoeffPowerWind=std(coeffPower(1:9,:))/sqrt(9);
meanCoeffPowerVacuum=mean(coeffPower(10:18,:));
errCoeffPowerVacuum=std(coeffPower(10:18,:))/sqrt(9);
figure('units','normalized','outerposition',[0 0 1 1])
plot(reducedFreq(1,:),coeffPower(1,:),'ro',...
    reducedFreq(2,:),coeffPower(2,:),'ro',...
    reducedFreq(3,:),coeffPower(3,:),'ro',...
    reducedFreq(4,:),coeffPower(4,:),'mo',...
    reducedFreq(5,:),coeffPower(5,:),'mo',...
    reducedFreq(6,:),coeffPower(6,:),'mo',...
    reducedFreq(7,:),coeffPower(7,:),'co',...
    reducedFreq(8,:),coeffPower(8,:),'co',...
    reducedFreq(9,:),coeffPower(9,:),'co',...
    reducedFreq(10,:),coeffPower(10,:),'g*',...
    reducedFreq(11,:),coeffPower(11,:),'g*',...
    reducedFreq(12,:),coeffPower(12,:),'g*',...
    reducedFreq(13,:),coeffPower(13,:),'b*',...
    reducedFreq(14,:),coeffPower(14,:),'b*',...
    reducedFreq(15,:),coeffPower(15,:),'b*',...
    reducedFreq(16,:),coeffPower(16,:),'k*',...
    reducedFreq(17,:),coeffPower(17,:),'k*',...
    reducedFreq(18,:),coeffPower(18,:),'k*');hold on;
errorbar(reducedFreq(1,:),meanCoeffPowerWind,errCoeffPowerWind,'-r');hold on;
errorbar(reducedFreq(1,:),meanCoeffPowerVacuum,errCoeffPowerWind,'-.g');hold on;
grid on
%title('Mean Coefficient of Power vs Reduced Frequency - 100% Rigid Wing')
set(gca, 'FontName', 'Arial')
set(gca, 'FontSize', 16)
ylabel('Coefficient of Power (Cp)')
xlabel('Reduced Frequency')
legend('Wind tunnel Set 1 Trial 1',...
    'Wind tunnel Set 1 Trial 2',...
    'Wind tunnel Set 1 Trial 3',...
    'Wind tunnel Set 2 Trial 1',...
    'Wind tunnel Set 2 Trial 2',...
    'Wind tunnel Set 2 Trial 3',...
    'Wind tunnel Set 3 Trial 1',...
    'Wind tunnel Set 3 Trial 2',...
    'Wind tunnel Set 3 Trial 3',...
    'Vacuum chamber Set 1 Trial 1',...
    'Vacuum chamber Set 1 Trial 2',...
    'Vacuum chamber Set 1 Trial 3',...
    'Vacuum chamber Set 2 Trial 1',...
    'Vacuum chamber Set 2 Trial 2',...
    'Vacuum chamber Set 2 Trial 3',...
    'Vacuum chamber Set 3 Trial 1',...
    'Vacuum chamber Set 3 Trial 2',...
    'Vacuum chamber Set 3 Trial 3',...
    'Wind tunnel Mean Cp with Standard Error',...
    'Vacuum chamber Mean Cp with Standard Error',...
    'Location','Northwest')